// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgeN1BWbmyDGClwmQhKV7ReFIfGUkxRE',
    appId: '1:148853012767:web:fb342d82574ceda47a182a',
    messagingSenderId: '148853012767',
    projectId: 'chatapp-7b7b1',
    authDomain: 'chatapp-7b7b1.firebaseapp.com',
    storageBucket: 'chatapp-7b7b1.appspot.com',
    measurementId: 'G-4TFN59X7Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsnayUDYArG2sOJrYw5UGV4PRpC-MSATw',
    appId: '1:148853012767:android:6622a92bba7024067a182a',
    messagingSenderId: '148853012767',
    projectId: 'chatapp-7b7b1',
    storageBucket: 'chatapp-7b7b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDhZ84NVSnWbNse0bgveuc13ss5rNoSY',
    appId: '1:148853012767:ios:a00af897b05bc4aa7a182a',
    messagingSenderId: '148853012767',
    projectId: 'chatapp-7b7b1',
    storageBucket: 'chatapp-7b7b1.appspot.com',
    androidClientId: '148853012767-6c41bin8bp16jl96dpok847rvu5th2o4.apps.googleusercontent.com',
    iosClientId: '148853012767-ulmdnce4plf8hurv4n9iov90snsfb08i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDhZ84NVSnWbNse0bgveuc13ss5rNoSY',
    appId: '1:148853012767:ios:a00af897b05bc4aa7a182a',
    messagingSenderId: '148853012767',
    projectId: 'chatapp-7b7b1',
    storageBucket: 'chatapp-7b7b1.appspot.com',
    androidClientId: '148853012767-6c41bin8bp16jl96dpok847rvu5th2o4.apps.googleusercontent.com',
    iosClientId: '148853012767-ulmdnce4plf8hurv4n9iov90snsfb08i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
